name: Auto Update News

on:
  schedule:
    - cron: "0 6,11,17 * * *"  # 7am, 12pm, and 6pm Nigeria time (UTC+1)
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Override Git Remote URL
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/anthonob/nigerian-news-aggregator.git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install torch
        pip install pandas beautifulsoup4 feedparser transformers requests

    - name: Run update script
      run: |
        python update_news.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add summarized_news.csv
        git commit -m "Auto-update summarized news" || echo "No changes to commit"
        git push origin HEAD:main
