name: Auto Update News

on:
  schedule:
    - cron: "0 6,11,17 * * *"   # 7 AM, 12 PM, 6 PM Nigeria time (UTC+1)
  workflow_dispatch:           # manual trigger via GitHub UI

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Git for push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/anthonob/nigerian-news-aggregator.git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install torch
        pip install pandas beautifulsoup4 feedparser transformers requests

    - name: Run update script
      run: python update_news.py

    - name: Commit & push if changed
      run: |
        git add summarized_news.csv
        git commit -m "Auto-update summarized news" || echo "No changes to commit"
        git push origin HEAD:main
